---
name: Checks

on: [push, pull_request_review]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Test
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          ALLOWED_HOSTS: ${{ secrets.ALLOWED_HOSTS }}
          DEBUG: ${{ secrets.DEBUG }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASS: ${{ secrets.DB_PASS }}
        run: docker-compose run -v "$PWD/shared:/shared" app sh -c "mkdir shared && 
             python manage.py wait_for_db &&
             coverage run manage.py test && coverage report && mv .coverage shared"

      - name: Verificar existencia do arquivo
        run: docker-compose run app sh -c "ls -a ./shared/"

      - name: Copiar os arquivos
        run: docker-compose --help

      - uses: codecov/codecov-action@v3
        with:
          files: ./shared/.codecov
          verbose: true # optional (default = false)
          
      - name: Pylint
        run: docker-compose run --rm app sh -c "pylint *"

      - name: Flake8
        run: docker-compose run --rm app sh -c "flake8"
        
      
      
